# Generated by Django 5.1.1 on 2024-10-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_follows_customuser_is_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('DEVELOPER', 'Développeur')], default='USER', max_length=10),
        ),
    ]
