# Generated by Django 5.1.1 on 2024-10-09 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_follows_userfollows'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(related_name='is_followed_by', through='authentication.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
