# Generated by Django 5.1.1 on 2024-10-16 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_follows'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(related_name='is_followed_by', through='subscriptions.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
